### ISSUE TITLE
How to disable Class Coverage to prevent assertion errors?

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-process-test-coverage#21]
I want to test different process models in one test class. Can I prevent this error:
> AssertionError: Class coverage can only be calculated if all tests deploy the same BPMN resources.

**Comment by ingorichtsmeier** [comment]
As a workaround, you can deploy the process to every test method of the class.

Background: During the camunda training you start to test the decision table in the last lab. Then the error occurs. If you deploy the process.bpmn even to the dmn tests (although you don't need them here) the assertion error disappears.

**Comment by martinschimak** [comment]
Just in case you are not aware... the TestCoverageProcessEngineRuleBuilder already has an "assertClassCoverageAtLeast" method which could be set to 0 and an "excludeProcessDefinitionKeys" method. Unsure whether that applies to your scenario... but you could try it, I did not test it, just saw your comments here.

**Comment by berndruecker** [comment]
@falko: Just change 
`
@ClassRule`

to

`@Rule`

and no coverage report for the whole class is generated - which is the use case you are striving for I think

**Comment by falko** [comment]
thx.

**Comment by suneel-kms123** [comment]
> @falko: Just change
> ` @ClassRule`
> 
> to
> 
> `@Rule`
> 
> and no coverage report for the whole class is generated - which is the use case you are striving for I think.
> 
> I think it could be closed - but probably some docs can be improved to reflect this?

when i change as per your suggestion, i get an error on 2nd test: 
org.camunda.bpm.engine.ProcessEngineException: ENGINE-03017 Could not perform operation 'create' on database schema for SQL Statement: '-- 
-- 
-- 
-- 
-- 
create table ACT_HI_PROCINST ( 
ID_ varchar(64) not null, 
PROC_INST_ID_ varchar(64) not null, 
BUSINESS_KEY_ varchar(255), 
PROC_DEF_KEY_ varchar(255), 
PROC_DEF_ID_ varchar(64) not null, 
START_TIME_ timestamp not null, 
END_TIME_ timestamp, 
REMOVAL_TIME_ timestamp, 
DURATION_ bigint, 
START_USER_ID_ varchar(255), 
START_ACT_ID_ varchar(255), 
END_ACT_ID_ varchar(255), 
SUPER_PROCESS_INSTANCE_ID_ varchar(64), 
ROOT_PROC_INST_ID_ varchar(64), 
SUPER_CASE_INSTANCE_ID_ varchar(64), 
CASE_INST_ID_ varchar(64), 
DELETE_REASON_ varchar(4000), 
TENANT_ID_ varchar(64), 
STATE_ varchar(255), 
primary key (ID_), 
unique (PROC_INST_ID_) 
)'.

	at org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.performDatabaseOperationException(EnginePersistenceLogger.java:230)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:690)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:617)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeMandatorySchemaResource(DbSqlSession.java:427)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.dbSchemaCreateHistory(DbSqlSession.java:362)
	at org.camunda.bpm.engine.impl.db.AbstractPersistenceSession.dbSchemaCreate(AbstractPersistenceSession.java:95)
	at org.camunda.bpm.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:51)
	at org.camunda.bpm.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:33)
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:27)
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:106)
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:69)
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:32)
	at org.camunda.bpm.engine.impl.ProcessEngineImpl.executeSchemaOperations(ProcessEngineImpl.java:119)
	at org.camunda.bpm.engine.impl.ProcessEngineImpl.<init>(ProcessEngineImpl.java:92)
	at org.camunda.bpm.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:786)
	at com.bt.athena.mec.junit.BPMNTestEngine.<init>(BPMNTestEngine.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
Caused by: org.h2.jdbc.JdbcSQLException: Table "ACT_HI_PROCINST" already exists; SQL statement:
-- 
-- 
-- 
-- 
-- 
create table ACT_HI_PROCINST ( 
ID_ varchar(64) not null, 
PROC_INST_ID_ varchar(64) not null, 
BUSINESS_KEY_ varchar(255), 
PROC_DEF_KEY_ varchar(255), 
PROC_DEF_ID_ varchar(64) not null, 
START_TIME_ timestamp not null, 
END_TIME_ timestamp, 
REMOVAL_TIME_ timestamp, 
DURATION_ bigint, 
START_USER_ID_ varchar(255), 
START_ACT_ID_ varchar(255), 
END_ACT_ID_ varchar(255), 
SUPER_PROCESS_INSTANCE_ID_ varchar(64), 
ROOT_PROC_INST_ID_ varchar(64), 
SUPER_CASE_INSTANCE_ID_ varchar(64), 
CASE_INST_ID_ varchar(64), 
DELETE_REASON_ varchar(4000), 
TENANT_ID_ varchar(64), 
STATE_ varchar(255), 
primary key (ID_), 
unique (PROC_INST_ID_) 
) [42101-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:117)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:663)
	... 44 more

**Comment by suneel-kms123** [comment]
> > @falko: Just change
> > ` @ClassRule`
> > to
> > `@Rule`
> > and no coverage report for the whole class is generated - which is the use case you are striving for I think.
> > I think it could be closed - but probably some docs can be improved to reflect this?
> 
> ## when i change as per your suggestion, i get an error on 2nd test:
> org.camunda.bpm.engine.ProcessEngineException: ENGINE-03017 Could not perform operation 'create' on database schema for SQL Statement: '--
> ## --
> --
> create table ACT_HI_PROCINST (
> ID_ varchar(64) not null,
> PROC_INST_ID_ varchar(64) not null,
> BUSINESS_KEY_ varchar(255),
> PROC_DEF_KEY_ varchar(255),
> PROC_DEF_ID_ varchar(64) not null,
> START_TIME_ timestamp not null,
> END_TIME_ timestamp,
> REMOVAL_TIME_ timestamp,
> DURATION_ bigint,
> START_USER_ID_ varchar(255),
> START_ACT_ID_ varchar(255),
> END_ACT_ID_ varchar(255),
> SUPER_PROCESS_INSTANCE_ID_ varchar(64),
> ROOT_PROC_INST_ID_ varchar(64),
> SUPER_CASE_INSTANCE_ID_ varchar(64),
> CASE_INST_ID_ varchar(64),
> DELETE_REASON_ varchar(4000),
> TENANT_ID_ varchar(64),
> STATE_ varchar(255),
> primary key (ID_),
> unique (PROC_INST_ID_)
> )'.
> 
> ```
> at org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.performDatabaseOperationException(EnginePersistenceLogger.java:230)
> at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:690)
> at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:617)
> at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeMandatorySchemaResource(DbSqlSession.java:427)
> at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.dbSchemaCreateHistory(DbSqlSession.java:362)
> at org.camunda.bpm.engine.impl.db.AbstractPersistenceSession.dbSchemaCreate(AbstractPersistenceSession.java:95)
> at org.camunda.bpm.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:51)
> at org.camunda.bpm.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:33)
> at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:27)
> at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:106)
> at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:69)
> at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:32)
> at org.camunda.bpm.engine.impl.ProcessEngineImpl.executeSchemaOperations(ProcessEngineImpl.java:119)
> at org.camunda.bpm.engine.impl.ProcessEngineImpl.<init>(ProcessEngineImpl.java:92)
> at org.camunda.bpm.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:786)
> at com.bt.athena.mec.junit.BPMNTestEngine.<init>(BPMNTestEngine.java:47)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
> at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
> at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
> at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
> at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
> ```
> 
> ## Caused by: org.h2.jdbc.JdbcSQLException: Table "ACT_HI_PROCINST" already exists; SQL statement:
> ## --
> ## --
> create table ACT_HI_PROCINST (
> ID_ varchar(64) not null,
> PROC_INST_ID_ varchar(64) not null,
> BUSINESS_KEY_ varchar(255),
> PROC_DEF_KEY_ varchar(255),
> PROC_DEF_ID_ varchar(64) not null,
> START_TIME_ timestamp not null,
> END_TIME_ timestamp,
> REMOVAL_TIME_ timestamp,
> DURATION_ bigint,
> START_USER_ID_ varchar(255),
> START_ACT_ID_ varchar(255),
> END_ACT_ID_ varchar(255),
> SUPER_PROCESS_INSTANCE_ID_ varchar(64),
> ROOT_PROC_INST_ID_ varchar(64),
> SUPER_CASE_INSTANCE_ID_ varchar(64),
> CASE_INST_ID_ varchar(64),
> DELETE_REASON_ varchar(4000),
> TENANT_ID_ varchar(64),
> STATE_ varchar(255),
> primary key (ID_),
> unique (PROC_INST_ID_)
> ) [42101-196]
> at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
> at org.h2.message.DbException.get(DbException.java:179)
> at org.h2.message.DbException.get(DbException.java:155)
> at org.h2.command.ddl.CreateTable.update(CreateTable.java:117)
> at org.h2.command.CommandContainer.update(CommandContainer.java:101)
> at org.h2.command.Command.executeUpdate(Command.java:260)
> at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
> at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
> at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:663)
> ... 44 more

I got the issue resoolved maybe i was doing it wrong.. I had one test class and two different test methods for 2 process model. processEngineRule is instantiated class variable with @Rule annotation. i wanted to avoid the test coverage which was throwing error, i acheived it with your comment but fell into this issue, but that was resolved by merging 2 methods into one. 

Sorry! sorry to bother you guys. :)
