### ISSUE TITLE
NPE in handleTestMethodCoverage if class is annotated with deployment

### ISSUE THREAD

**Issue by bs11234** [camunda/camunda-bpm-process-test-coverage#33]
If test class is annotated with deployment and `@ClassRule` is used to generate class diagram, a `NullPointerException` occurs in `handleTestMethodCoverage`.

Example code:

```
@Deployment(resources = { "Process.bpmn" })
public class ProcessTest {

	@Rule
	@ClassRule
	public static ProcessEngineRule rule = TestCoverageProcessEngineRuleBuilder.create().build();

	...
}
```

The following error occurs at the end of test execution:

```
java.lang.NullPointerException
	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.handleTestMethodCoverage(TestCoverageProcessEngineRule.java:307)
	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.finished(TestCoverageProcessEngineRule.java:144)
	at de.rewe.rekla.einarbeitung.process.TestCoverageSpringProcessEngineRule$1.evaluate(TestCoverageSpringProcessEngineRule.java:52)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

It seems that for final call variable testCoverage is null because testName is null.

The problem does not occur, if test methods instead of test class are annotated with `@Deployment`.

**Comment by bs11234** [comment]
Tested in v0.3.2
