### ISSUE TITLE
NPE in MethodCoverage.addCoveredElement when mocking call activity from embedded subprocess

### ISSUE THREAD

**Issue by JohnArray** [camunda/camunda-bpm-process-test-coverage#46]
While mocking call activity in embedded subprocess, NPE is thrown:
![bug](https://user-images.githubusercontent.com/30523656/64183153-b54b2700-ce69-11e9-985f-5031b6605b29.png)
Stack:
`java.lang.NullPointerException
	at org.camunda.bpm.extension.process_test_coverage.model.MethodCoverage.addCoveredElement(MethodCoverage.java:63)
	at org.camunda.bpm.extension.process_test_coverage.model.ClassCoverage.addCoveredElement(ClassCoverage.java:35)
	at org.camunda.bpm.extension.process_test_coverage.junit.rules.CoverageTestRunState.addCoveredElement(CoverageTestRunState.java:56)
	at org.camunda.bpm.extension.process_test_coverage.listeners.FlowNodeHistoryEventHandler.handleEvent(FlowNodeHistoryEventHandler.java:52)
	at org.camunda.bpm.engine.impl.history.parser.HistoryExecutionListener.notify(HistoryExecutionListener.java:59)
	at org.camunda.bpm.engine.impl.history.parser.HistoryExecutionListener.notify(HistoryExecutionListener.java:38)
	at org.camunda.bpm.engine.impl.core.instance.CoreExecution.invokeListener(CoreExecution.java:101)
	at org.camunda.bpm.engine.impl.core.operation.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:55)
	at org.camunda.bpm.engine.impl.interceptor.AtomicOperationInvocation.execute(AtomicOperationInvocation.java:96)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.invokeNext(CommandInvocationContext.java:128)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.performNext(CommandInvocationContext.java:108)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.performOperation(CommandInvocationContext.java:83)
	at org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:640)
	at org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:614)
	at org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationActivityStartCreateScope.scopeCreated(PvmAtomicOperationActivityStartCreateScope.java:43)
	at org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationCreateScope.execute(PvmAtomicOperationCreateScope.java:54)
	at org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationCreateScope.execute(PvmAtomicOperationCreateScope.java:28)
	at org.camunda.bpm.engine.impl.interceptor.AtomicOperationInvocation.execute(AtomicOperationInvocation.java:96)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.invokeNext(CommandInvocationContext.java:128)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.performNext(CommandInvocationContext.java:115)
	at org.camunda.bpm.engine.impl.interceptor.CommandInvocationContext.performOperation(CommandInvocationContext.java:83)
	at org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:640)
	at org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:614)
	at org.camunda.bpm.engine.impl.pvm.runtime.PvmExecutionImpl.start(PvmExecutionImpl.java:248)
	at org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.start(ExecutionEntity.java:449)
	at org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:66)
	at org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:38)
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:107)
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.executeWithVariablesInReturn(ProcessInstantiationBuilderImpl.java:166)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.execute(ProcessInstantiationBuilderImpl.java:132)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.execute(ProcessInstantiationBuilderImpl.java:128)
	at org.camunda.bpm.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:107)
	at org.camunda.bpm.scenario.impl.ProcessRunnerImpl$1.start(ProcessRunnerImpl.java:146)
	at org.camunda.bpm.scenario.impl.ProcessRunnerImpl.run(ProcessRunnerImpl.java:174)
	at org.camunda.bpm.scenario.impl.ProcessRunnerImpl.next(ProcessRunnerImpl.java:185)
	at org.camunda.bpm.scenario.impl.ScenarioImpl.execute(ScenarioImpl.java:38)
	at org.camunda.bpm.scenario.impl.ProcessRunnerImpl.execute(ProcessRunnerImpl.java:119)`

Works fine outside embedded suubprocess

**Comment by voidkor** [comment]
I had the same problem. As a work around you can exclude the `processDefinitionKey` which you use in `CallActivityMock` from the process coverage engine like follow:
`rule = TestCoverageProcessEngineRuleBuilder.create(processEngine) .excludeProcessDefinitionKeys("MOCKED_PROCESS_KEY").build();`
It helped me.
