### ISSUE TITLE
Java 11 issue

### ISSUE THREAD

**Issue by javabean68** [camunda/camunda-bpm-process-test-coverage#49]
Hi all,

first off compliments for your tool: really useful!

I'm trying to understand how to configure it but I get no image generated only html...

I think that has with this exception to do:

`Apr 12, 2020 1:03:25 PM org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule handleTestMethodCoverage
INFO: testGo test method coverage is 0.7777777777777778
**Apr 12, 2020 1:03:25 PM org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil installBowerComponents
SEVERE: Unable to copy bower_components!
java.lang.NullPointerException**
	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.installBowerComponents(CoverageReportUtil.java:174)
	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.createReport(CoverageReportUtil.java:79)
	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.createCurrentTestMethodReport(CoverageReportUtil.java:64)
	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.handleTestMethodCoverage(TestCoverageProcessEngineRule.java:315)
	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.finished(TestCoverageProcessEngineRule.java:144)
	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:165)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:165)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)`

I'm using openjdk 1.8.0 _191 on Linux RedHat 7 with maven.
<spring.boot.version>2.2.1.RELEASE</spring.boot.version>
<camunda.spring.boot.starter.version>3.4.0</camunda.spring.boot.starter.version>

It seems the same problem as in https://github.com/camunda/camunda-bpm-process-test-coverage/issues/5 but I don't understand how to fix it in my environment
Many thanks for any tip in advance,
Best regards,
Fabio

**Comment by falko** [comment]
As a workaround you could try copying the `bower_components` folder from [here](https://github.com/camunda-consulting/code/tree/e353d182076f8b83092a91807811ed856ce84eac/snippets/bpmn-transaction/docs/process-test-coverage/bower_components) or [here](https://github.com/camunda-consulting/code/tree/master/snippets/process-test-coverage/src/main/resources).

**Comment by javabean68** [comment]
Hallo Falko,

many thanks for your reply. It was a stupid error of mine: I didn't notice
I was using java 11 instead of 8.

Sorry!
Best regards,
Fabio


Am Di., 14. Apr. 2020 um 12:52 Uhr schrieb Falko Menge <
notifications@github.com>:

**Comment by falko** [comment]
Okay, great to head that you got it to work. Then the issue should be renamed to reflect that it seems to be a Java 11 issue.
